version: '3.8'

services:
  permission-api:
    image: permission-api
    container_name: permission-api
    hostname: permission-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - AUTH_STRATEGY=${AUTH_STRATEGY}
      - AUTH0_ISSUER=${AUTH0_ISSUER}
      - AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}
      - API_KEYS=${API_KEYS}
      - AWS_CLIENT_ID=${AWS_CLIENT_ID}
      - AWS_CLIENT_SECRET=${AWS_CLIENT_SECRET}
      - AWS_DYNAMO_ENDPOINT=${AWS_DYNAMO_ENDPOINT}
      - AWS_DYNAMO_PERMISSION_TABLE_NAME=${AWS_DYNAMO_PERMISSION_TABLE_NAME}
      - AWS_REGION=${AWS_REGION}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - 3010:80
    platform: linux/amd64
    restart: always

networks:
  default:
    external: true
    name: local-network