version: '3.8'

services:
  permission-api:
    image: permission-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3010:80
    platform: linux/amd64
    restart: always

networks:
  default:
    external: true
    name: local-network